version : "1"

services:
  rtc-fe:
    build : ./client
    ports:
      - "5173:5173"
    env_file:
      - .env.production
    volumes:
      - ./client:/app
      - /app/node_modules

  rtc-backend:
    build: ./server
    ports:
      - "4000:4000"
    env_file:
      - .env.production
    volumes:
      - ./server:/app
      - /app/node_modules